### PR TITLE
#21: Update Converse to 5.0.5

### PR DESCRIPTION
**Pull request by mnsuccess**
A new version of Converse was released. This PR  makes use of that version  (converse 5.0.5).
https://github.com/igniterealtime/openfire-inverse-plugin/issues/21

### CODE REVIEW

**Comment by guusdk** [comment]
Thanks @mnsuccess ! I'll look at this tomorrow!

Did you apply a change to the Converse distribution files similar as the one I did in f56d8b93d2c32bfeb94350464f2c843e98bbd1c6 (when I updated to the previous release)?

If you didn't do that yet, please do it (or things will break).

If you already did it: can you please split the one commit that you have now into two, so that we have one commit that replaces all (Converse) files, and another commit that applies to change to the dist files?

**Comment by mnsuccess** [comment]
> Thanks @mnsuccess ! I'll look at this tomorrow!
> 
> Did you apply a change to the Converse distribution files similar as the one I did in [f56d8b9](https://github.com/igniterealtime/openfire-inverse-plugin/commit/f56d8b93d2c32bfeb94350464f2c843e98bbd1c6) (when I updated to the previous release)?
> 
> If you didn't do that yet, please do it (or things will break).
> 
> If you already did it: can you please split the one commit that you have now into two, so that we have one commit that replaces all (Converse) files, and another commit that applies to change to the dist files?

Not yet .. let me work on that .. I didn't pay any attention to do it.

**Comment by guusdk** [comment]
Looks pretty good! There's a minor problem in the changelog:

image

Besides that, I think we only need the change from f56d8b93d2c32bfeb94350464f2c843e98bbd1c6 being applied here too. Without it, the UI is broken:

image

**Comment by guusdk** [comment]
Awesome! This seems to work just fine in my tests! Thanks!

**Pull request merged**
