### PR TITLE
#24: Update Converse to 6.0.0

### PR DESCRIPTION
**Pull request by mnsuccess**
A new version of Converse was released. This PR  makes use of that version  (converse 6.0.0).
https://github.com/igniterealtime/openfire-inverse-plugin/issues/24

### CODE REVIEW

**Comment by guusdk** [comment]
Thanks for this! A couple of requests:

- please make the version number in the pom 6.0.0.0-SNAPSHOT (instead of 6.0.0-SNAPSHOT)
- please rebase it on the latest commit on the MASTER branch
- please review the "breaking changes" as they are documented in the release notes. I think that we need a change, because we use 'debug'

> The debug configuration option has been replaced with loglevel.

**Comment by guusdk** [comment]
Thanks @mnsuccess ! Can you also rebase the PR please?

**Comment by mnsuccess** [comment]
> Thanks @mnsuccess ! Can you also rebase the PR please?

How do I have to do to rebase this PR?

**Comment by guusdk** [comment]
See https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request (or any of a number of other tutorials).

**Comment by mnsuccess** [comment]
> See https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request (or any of a number of other tutorials).



> Thanks @mnsuccess ! Can you also rebase the PR please?

I tried  to rebase but everything is up-to-date

**Comment by guusdk** [comment]
That's odd. Why do I get this then?

image

**Comment by mnsuccess** [comment]
> That's odd. Why do I get this then?
> 
> image

Screenshot 2020-02-12 at 18 04 43
It's weird. It shows something different from me

**Comment by guusdk** [comment]
Use this button:

image

I always prefer to rebase, instead of merge. The fact that github cannot rebase suggests that there is some kind of conflict that should be resolved, I think.

**Comment by mnsuccess** [comment]
> Use this button:
> 
> image
> 
> I always prefer to rebase, instead of merge. The fact that github cannot rebase suggests that there is some kind of conflict that should be resolved, I think.

okay, let me investigate on that !! thanks

**Comment by mnsuccess** [comment]
I have decided to close this PR then create a new one

**Comment by guusdk** [comment]
The new PR (to replace this PR) can be found at at https://github.com/igniterealtime/openfire-inverse-plugin/pull/26

**Pull request closed without merging**
