### PR TITLE
#4 Simplify version identifier.

### PR DESCRIPTION
**Pull request by guusdk**
Up until now, the version identifier was formatted as:

    <major>.<minor>.<patch> RELEASE <increment>

where everything before 'release' matches the version of the upstream
Converse dependency. This format proves difficult to work with, as it
doesn't play nice with the combination of IgniteRealtime website, Maven,
and Openfire-based version identifier parsing.

This commit reverts back to a simpler format. We'll have to figure out
a different way to denote multiple builds based on the same version of
Converse (but to date, that hasn't happened yet - jinxing it as I write
this).

### CODE REVIEW

**Comment by GregDThomas** [comment]
You should be able to get away with a "fourth" dot.

So 4.0.6.1-SNAPSHOT (in the pom.xml/plugin.xml) becomes the first release of the plugin with Converse 4.0.6, etc.

**Comment by guusdk** [comment]
I just verified that Openfire likes the fouth dot. That's awesome! Didn't know that one. Let's see if the website likes that too.

**Comment by GregDThomas** [comment]
Bah. As I suspected, the website @ https://www.igniterealtime.org/projects/openfire/plugin-archive.jsp?plugin=inverse is showing "4.1.0.1" compared with the Openfire "4.1.0 Release 1"

**Comment by guusdk** [comment]
4.3.0 (Ignite's). I tested this, but missed something, apparently.

**Pull request merged**
